### ISSUE TITLE
Tweedie distribution

### ISSUE THREAD

**Issue by nickcorona** [malmgrek/gammy#3]
Is there a way to fit a gam with a Tweedie distribution?

A Tweedie distribution is a mixture between a poison and a gamma distribution. It helps model insurance losses with a significant positive probability mass at 0 (because most customers do not claim losses).

**Comment by malmgrek** [comment]
Currently there is no out-of-the-box utility for defining a Tweedie distribution. Do you know a good reference for computation of Tweedie distribution's covariance kernel?
